@host=http://localhost:4444

GET {{host}}
###

GET {{host}}/test-error
###

GET {{host}}/api/v1/users?index=0&limit=10
###

GET {{host}}/api/v1/users?index=0&limit=10&filter=dass
###

GET {{host}}/api/v1/users/4
###

POST {{host}}/api/v1/users
Content-Type: application/json

{
    "email": "test1@test.com",
    "phone": "81 900000001",
    "name": "Test 1",
    "cpf": "000.000.000-00",
    "login": "test",
    "password": "test123",
    "age": "2023-08-25"
}
###

POST {{host}}/api/v1/users
Content-Type: application/json

{
    "email": "test2@test.com",
    "phone": "81 900000001",
    "name": "Test 2",
    "cpf": "000.000.000-01",
    "login": "test2",
    "password": "test123",
    "age": "2023-08-25"
}
###

GET {{host}}/api/v1/users/5
###

PUT {{host}}/api/v1/users/5
Content-Type: application/json

{
    "email": "test1B@test.com"
}
###

PUT {{host}}/api/v1/users/5
Content-Type: application/json

{
    "password": "test123B"
}
###

PUT {{host}}/api/v1/users/5
Content-Type: application/json

{
    "name": "Test 1 D"
}
###

GET {{host}}/api/v1/users/7
###

DELETE {{host}}/api/v1/users/7
###