export * from './InputData'
export * from './InputDataAge'
export * from './InputDataCPF'
export * from './InputDataEmail'
export * from './InputDataLogin'
export * from './InputDataName'
export * from './InputDataPassword'
export * from './InputDataPhone'